services:
  linkedin-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkedin-bot
    volumes:
      - ./config.py:/app/config.py
      - ./images:/app/images
      - ./chrome-profile:/app/chrome-profile
    environment:
      - DISPLAY=:99
    ports:
      - "5900:5900"
    # command: >
    #   /bin/sh -c "Xvfb :99 -screen 0 1920x1080x24 & 
    #               python3 main.py"
    # Optionnel — retirer network_mode et ipc si tu n'as pas besoin de l'affichage local externe
    network_mode: host
    ipc: host
